---
title: "Prior setting data analysis"
author: ""
date: "8/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidybayes)
library(magrittr)
```

## Clean the data

```{r data-clean, eval = FALSE}
data.raw = read_csv( file = "data/prior-setting-study.csv", 
                 col_types = list())

data.raw %>%
  rename( 
    t3 = `Duration (in seconds)`,
    `Confidence in answer` = Q1_1,
    `Previous stats analysis` = Q2,
    `Stats software` = Q3,
    `Knowledge software` = Q4,
    `Knowledge stats` = Q5,
    `Knowledge Bayesian` = Q6,
    Strategy = Q7,
    `Affect of choice` = Q8,
    Education = Q9,
    condition = cond
  ) %>%
  select(t3, ResponseId, `Confidence in answer`:Education, alpha:t2) %>%
  extract( 3:nrow(.), ) %>%
  mutate(
    t1 = as.numeric(t1),
    t2 = as.numeric(t2),
    t3 = as.numeric(t3),
    time = t1 + t2 + t3
  ) %>%
  select (t1, t2, t3, time, everything()) %>%
  write.csv( file = "data/prior-setting-study-deidentified.csv", row.names = FALSE )
```

## Load the data

```{r data}
data = read_csv( file = "data/prior-setting-study-deidentified.csv", 
                 col_types = list())
```

Check the number of responses in each condition

```{r}
data %>%
  group_by(condition) %>%
  summarise(n = n())
```

Calculate the amount of time spent by the participants in the  survey:

```{r}
data %>%
  mutate( time = (as.numeric(t1) + as.numeric(t2)) ) %>%
  mutate( t3 = (as.numeric(t3)) ) %>%
  summarise( 
    median = median(time), 
    sd = sd(time),
    median_qualtrics = median(t3),
    sd_qualtrics = sd(t3)
  )
```


```{r}
priors <- data %>%
  select( ResponseId, condition, alpha, beta ) %>%
  gather( parameter, prior, alpha, beta ) %>%
  separate( col = prior, into = c("dist", "mu", "sigma"), sep = "([\\(,\\)])", extra = "drop" ) %>%
  mutate( 
    dist = replace(dist, dist == "N", "normal"),
    dist = replace(dist, dist == "t", "student_t")
  ) %>%
  mutate( mu = as.numeric(mu), sigma = as.numeric(sigma) )

get_density <- function( dist, mu, sigma, grid) {
  if (dist == "normal") {
    dnorm( grid, mu, sigma )
  } else if(dist == "student_t") {
    gamlss.dist::dTF( grid, mu, sigma, nu = 3)
  } else {
    NA
  }
}

get_density_response <- function( dist, mu, sigma, grid) {
  if (dist == "normal") {
    dnorm( log(grid), mu, sigma ) * abs( 1/grid)
  } else if(dist == "student_t") {
    gamlss.dist::dTF(log(grid), mu, sigma, nu = 3) * abs( 1/grid)
  } else {
    NA
  }
}
```

```{r, priors-intercept, fig.height = 4, fig.width = 12}
priors.dens.alpha <- priors %>% 
  filter( parameter == "alpha" ) %>%
  mutate( grid = list(seq(-1, 7, by = 0.01)) ) %>%
  mutate( density = pmap(list(dist, mu, sigma, grid), ~ get_density(..1, ..2, ..3, ..4)) )

priors.dens.alpha %>%
  unnest( grid, density, .drop = FALSE) %>%
  drop_na() %>%
  ggplot() +
  geom_vline( xintercept = log(35), alpha = 0.5 ) +
  geom_line(aes( x = grid, y = density, color = dist, group = ResponseId), alpha = 0.7) +
  facet_wrap( ~ condition)
```


```{r, priors-intercept-response, fig.height = 6, fig.width = 12}
priors.dens_response.alpha <- priors %>% 
  filter( parameter == "alpha" ) %>%
  mutate( grid = list(seq(0.5, 200, by = 0.5)) ) %>%
  mutate( density = pmap(list(dist, mu, sigma, grid), ~ get_density_response(..1, ..2, ..3, ..4)) ) %>%
  unnest( grid, density, .drop = FALSE)
  
df.interval = tibble( x = c(24.6, 44.1), y = range(priors.dens_response.alpha$density)) %>%
  gather("axis", "value", x, y) %>%
  mutate( axis = c("x.lower", "x.upper", "y.lower", "y.upper")) %>%
  spread( axis, value)

priors.dens_response.alpha %>%
  unnest( grid, density, .drop = FALSE) %>%
  drop_na() %>%
  ggplot() +
  geom_rect( data = df.interval, aes(xmin = x.lower, xmax = x.upper, ymin = y.lower, ymax = y.upper), fill = "grey50", alpha = 0.3 ) +
  geom_line(aes( x = grid, y = density, color = dist, group = ResponseId), alpha = 0.7) +
  facet_grid(condition ~ .)
```


```{r, priors-intercept-hist, fig.height = 4, fig.width = 12}
priors %>% 
  filter( parameter == "alpha" ) %>%
  drop_na() %>%
  ggplot() +
  geom_vline( xintercept = log(35), alpha = 0.5 ) +
  geom_histogram(aes( x = mu, group = ResponseId), alpha = 0.7, binwidth = 0.1) +
  facet_wrap( ~ condition)
```


```{r, priors-intercept-sd-hist, fig.height = 4, fig.width = 12}
priors %>% 
  filter( parameter == "alpha" ) %>%
  drop_na() %>%
  ggplot() +
  geom_histogram(aes( x = sigma, group = ResponseId), alpha = 0.7, binwidth = 0.1) +
  facet_wrap( ~ condition)
```


```{r, priors-meandiff, fig.height = 4, fig.width = 12}
priors.dens.beta <- priors %>% 
  filter( parameter == "beta" ) %>%
  mutate( grid = list(seq(-2, 2, by = 0.01)) ) %>%
  mutate( density = pmap(list(dist, mu, sigma, grid), ~ get_density(..1, ..2, ..3, ..4)) )

priors.dens.beta %>%
  unnest( grid, density, .drop = FALSE) %>%
  drop_na() %>%
  ggplot() +
  geom_vline( xintercept = 0, alpha = 0.5 ) +
  geom_line(aes( x = grid, y = density, color = dist, group = ResponseId), alpha = 0.7) +
  facet_wrap( ~ condition)
```


```{r, priors-meandiff-response, fig.height = 4, fig.width = 12}
priors.dens.beta <- priors %>% 
  filter( parameter == "beta" ) %>%
  mutate( grid = list(seq(-2.5, 2.5, by = 0.01)) ) %>%
  mutate( density = pmap(list(dist, mu, sigma, grid), ~ get_density(..1, ..2, ..3, ..4)) )

priors.dens.beta %>%
  unnest( grid, density, .drop = FALSE) %>%
  drop_na() %>%
  ggplot() +
  geom_vline( xintercept = 0, alpha = 0.5 ) +
  geom_line(aes( x = grid, y = density, color = dist, group = ResponseId), alpha = 0.7) +
  scale_x_continuous( breaks = log(c(0.1, 0.2, 0.4, 0.7, 1, 1.4, 2, 3, 5)), labels = function(x) round(exp(x), 2) ) +
  facet_wrap( ~ condition)
```



```{r, priors-meandiff-hist, fig.height = 4, fig.width = 12}
priors %>% 
  filter( parameter == "beta" ) %>%
  drop_na() %>%
  ggplot() +
  geom_vline( xintercept = 0, alpha = 0.5 ) +
  geom_histogram(aes( x = mu, group = ResponseId), alpha = 0.7, binwidth = 0.1) +
  facet_wrap( ~ condition)
```


```{r, priors-intercept-sd-hist, fig.height = 4, fig.width = 12}
priors %>% 
  filter( parameter == "beta" ) %>%
  drop_na() %>%
  ggplot() +
  geom_histogram(aes( x = sigma, group = ResponseId), alpha = 0.7, binwidth = 0.1) +
  facet_wrap( ~ condition)
```



## Calculating the prior predictive density

$$
\begin{aligned}
f(k; \mu, \sigma | control) & = \int{ f_{poisson(\lambda)}(k).f_{control}(\lambda)d\lambda } \\
& = \int{ \frac{\lambda^k}{k!} exp(-\lambda) \frac{1}{\lambda\sigma\sqrt{2\pi}}exp( - \frac{(ln \lambda - \mu)^2}{2\sigma^2} } d\lambda \\
& = \frac{1}{k!\sigma\sqrt{2\pi}}\int{ \lambda^{(k-1)} exp(-\lambda) exp( - \frac{(ln \lambda - \mu)^2}{2\sigma^2} }) d\lambda \\
\end{aligned}
$$


```{r}
integrand_control <- function(x, mu, sigma, k) {
  (x^(k - 1) * exp(-x - ((log(x) - mu)^2)/(2 * sigma^2) )) / ((sqrt(2*pi) * sigma * factorial(k)))
}

prior_predictive_density.control <- priors %>%
  filter( parameter == "alpha" & dist == "normal" ) %>%
  drop_na() %>%
  mutate( 
    k = list(seq(1, 128, by = 1))
  ) %>%
  unnest(k) %>%
  mutate(
    density = pmap_dbl( list(mu, sigma, k), ~integrate( integrand_control, lower = 0, upper = 200, mu = ..1, sigma = ..2, k = ..3)$value )
  )

prior_predictive_density.control %>%
  select(-k) %>%
  group_by( ResponseId, mu, sigma, parameter, dist ) %>%
  summarise( density = sum(density) )
```


